[package]
name = "rust-gamepad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"


[[example]]
name = "hello-xbox"
path = "examples/hello-xbox/main.rs"
